import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";

const roboto = Roboto({
  variable : "--font-roboto",
  subsets :["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <ThemeProvider>
          <Navbar />
          <main className="px-4 py-6">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
